"""add sources fetch runs and candidates

Revision ID: 215989b8f3ac
Revises: 5597f56f55d3
Create Date: 2026-09-01 23:09:41.091384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215989b8f3ac'
down_revision = '5597f56f55d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('rss', 'web')", name='ck_sources_source_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_last_fetched_at'), ['last_fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_url'), ['url'], unique=True)

    op.create_table('fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='ck_fetch_runs_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_runs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_status'), ['status'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_url', sa.String(length=1000), nullable=False),
    sa.Column('original_summary', sa.Text(), nullable=True),
    sa.Column('original_author', sa.String(length=240), nullable=True),
    sa.Column('published_at_source', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('converted_article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('new', 'review', 'rejected', 'converted')", name='ck_candidates_status'),
    sa.ForeignKeyConstraint(['converted_article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_converted_article_id'), ['converted_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_original_url'), ['original_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidates_published_at_source'), ['published_at_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_candidates_source_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_published_at_source'))
        batch_op.drop_index(batch_op.f('ix_candidates_original_url'))
        batch_op.drop_index(batch_op.f('ix_candidates_converted_article_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_runs_status'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_source_id'))

    op.drop_table('fetch_runs')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_url'))
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_sources_last_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_sources_is_active'))

    op.drop_table('sources')
    # ### end Alembic commands ###
