"""add source quality score

Revision ID: 3eb3f9372a5d
Revises: 917d0951fd41
Create Date: 2026-09-03 15:42:04.928567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb3f9372a5d'
down_revision = '917d0951fd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'quality_score',
                sa.Integer(),
                server_default='5',
                nullable=False,
            )
        )
        batch_op.create_check_constraint(
            'ck_sources_quality_score',
            'quality_score BETWEEN 0 AND 10',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_sources_quality_score',
            type_='check',
        )
        batch_op.drop_column('quality_score')

    # ### end Alembic commands ###
