"""initial phase 1 schema

Revision ID: 51decca96cc4
Revises: 
Create Date: 2026-09-01 20:35:27.285680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51decca96cc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_visible'), ['visible'], unique=False)

    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=160), nullable=False),
    sa.Column('arabic_site_name', sa.String(length=160), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('hero_title', sa.String(length=300), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=False),
    sa.Column('footer_text', sa.String(length=300), nullable=False),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('favicon_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_site_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('bg', sa.String(length=7), nullable=False),
    sa.Column('bg_secondary', sa.String(length=7), nullable=False),
    sa.Column('panel', sa.String(length=7), nullable=False),
    sa.Column('text', sa.String(length=7), nullable=False),
    sa.Column('text_muted', sa.String(length=7), nullable=False),
    sa.Column('primary', sa.String(length=7), nullable=False),
    sa.Column('secondary', sa.String(length=7), nullable=False),
    sa.Column('lime', sa.String(length=7), nullable=False),
    sa.Column('cyan', sa.String(length=7), nullable=False),
    sa.Column('pink', sa.String(length=7), nullable=False),
    sa.Column('border', sa.String(length=7), nullable=False),
    sa.Column('button', sa.String(length=7), nullable=False),
    sa.Column('hover', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_themes_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_themes_is_active'))

    op.drop_table('themes')
    op.drop_table('site_settings')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_visible'))
        batch_op.drop_index(batch_op.f('ix_categories_sort_order'))
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
