"""add arabic candidate fields

Revision ID: 6ff3af524cdf
Revises: 215989b8f3ac
Create Date: 2026-09-02 09:31:25.567491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff3af524cdf'
down_revision = '215989b8f3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arabic_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('arabic_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('arabic_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('translation_status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.create_index(batch_op.f('ix_candidates_translation_status'), ['translation_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_translation_status'))
        batch_op.drop_column('translation_status')
        batch_op.drop_column('arabic_body')
        batch_op.drop_column('arabic_summary')
        batch_op.drop_column('arabic_title')

    # ### end Alembic commands ###
