"""add candidate content scoring fields

Revision ID: 917d0951fd41
Revises: eb09c0db6ac6
Create Date: 2026-09-03 14:36:06.124282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917d0951fd41'
down_revision = 'eb09c0db6ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevance_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('practical_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('knowledge_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('adaptability_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_quality_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('originality_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overall_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('score_recommendation', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('scoring_reasons', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scored_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_candidates_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_score_recommendation'), ['score_recommendation'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_scored_at'), ['scored_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_scored_at'))
        batch_op.drop_index(batch_op.f('ix_candidates_score_recommendation'))
        batch_op.drop_index(batch_op.f('ix_candidates_overall_score'))
        batch_op.drop_index(batch_op.f('ix_candidates_content_type'))
        batch_op.drop_column('scored_at')
        batch_op.drop_column('scoring_reasons')
        batch_op.drop_column('score_recommendation')
        batch_op.drop_column('content_type')
        batch_op.drop_column('overall_score')
        batch_op.drop_column('originality_score')
        batch_op.drop_column('source_quality_score')
        batch_op.drop_column('adaptability_score')
        batch_op.drop_column('knowledge_score')
        batch_op.drop_column('practical_score')
        batch_op.drop_column('relevance_score')

    # ### end Alembic commands ###
