"""add candidate translation status constraint

Revision ID: d467e9d4fc3b
Revises: 6ff3af524cdf
Create Date: 2026-09-02 13:12:58.854002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd467e9d4fc3b'
down_revision = '6ff3af524cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_candidates_translation_status', "translation_status IN ('pending', 'translated', 'edited')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('ck_candidates_translation_status', type_='check')

    # ### end Alembic commands ###
