"""add original body to candidates

Revision ID: eb09c0db6ac6
Revises: d467e9d4fc3b
Create Date: 2026-09-03 11:33:57.166923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb09c0db6ac6'
down_revision = 'd467e9d4fc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('original_body')

    # ### end Alembic commands ###
